### ISSUE TITLE
Using TS constants in HTML is not possible in TYPO3 10 anymore

### ISSUE THREAD

**Issue by DrWh0286** [Xippo/OM-Cookie-Manager#11]
Unfortunately the feature to use TS constants in the HTML field to e.g.set different ids on different pages does not work anymore, because the method \TYPO3\CMS\Core\TypoScript\TemplateService::substituteConstants() is not public anymore. So trying this it fails with an error.

**Comment by Xippo** [comment]
Thx a lot for this submit and you contribution. I will check this ASAP for all TYPO3 supported versions.

**Comment by DrWh0286** [comment]
@Xippo No problem 🙂 . What's the current state of your review?

**Comment by Xippo** [comment]
Sorry for the late answer im a bit busy these days. Unfortunately i have still no time for testing jet. You can test the PR on your own  if you want and give me feedback. As temporarily solution you could still use a composer patch, if you need the change in production, so you don't have to wait my the tests. Sorry for keep you waiting.
