### ISSUE TITLE
Setting add to body doesn´t work

### ISSUE THREAD

**Issue by criwe** [Xippo/OM-Cookie-Manager#14]
Hi all!
Maybe someone can confirm that:

Changing the setting "Insert in" to "body" the setting is ignored (code still added in the header).

TYPO3 9.5.20
OM Cookie-Manager. 10.0.1

Best,
Christoph

**Comment by Xippo** [comment]
I have tested this on TYPO3 9.5.24 an TYPO3 10 without problems. Sorry i can't reproduce this one. 

Maybe more details about your setup could help. How many cookies you have in the specific group etc etc.

**Comment by Xippo** [comment]
closed due to inactivity
