### ISSUE TITLE
Missing extenison key

### ISSUE THREAD

**Issue by conpassione** [Xippo/OM-Cookie-Manager#16]
Composer beklagt fehlenden Extension Key:
The TYPO3 extension package "opfaff/om-cookie-manager", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

In die composer.json-Datei muss sowas integriert werden:
  "extra": {
    "typo3/cms": {
      "extension-key": "om-cookie-manager"
  	}
  }

**Comment by Xippo** [comment]
Thx for your report. The issue is solved with the new version which supports also TYPO 11
