### ISSUE TITLE
Revocable?

### ISSUE THREAD

**Issue by criwe** [Xippo/OM-Cookie-Manager#18]
Hi!
Is there a simple way (i.e. onlick-event) to call the cookiebanner again after closing it?
AFAIK that is a must have due to new TTDSG rules..

Thanks!
Christoph

**Comment by Xippo** [comment]
Hi Christoph,

As far as I know, this was already necessary in the GDPR. The extension
offers something like this in the info view. Generally, the opening of the
settings is triggered by all HTML tags (which have not been added via
JavaScript) that have data-omcookie-panel-show as an attribute.

>

**Comment by criwe** [comment]
Good evening!
Thanks a lot, works perfect :-)
