### ISSUE TITLE
Clear entries in deprecation log file for TYPO3 11

### ISSUE THREAD

**Issue by freshworkx** [Xippo/OM-Cookie-Manager#19]
There are many entries in the TYPO3 deprecation log file like:

`Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin with argument $extensionName ("OM.OmCookieManager") containing the vendor name ("OM") is deprecated and will stop working in TYPO3 11.0.`

`Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin with argument $extensionName ("OM.OmCookieManager") containing the vendor name ("OM") is deprecated and will stop working in TYPO3 11.0.`

`Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule with argument $extensionName containing the vendor name is deprecated and will stop working in TYPO3 11.0.`

`The 'tx_omcookiemanager_domain_model_cookie' TCA tables transOrigPointerField 'l10n_parent' is defined  as excluded field which is no longer needed and should therefore be removed.`

`The 'tx_omcookiemanager_domain_model_cookie' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.`

`The TCA field 'sys_language_uid' of table 'tx_omcookiemanager_domain_model_cookie' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'.`

Please clean up your `TCA` / `ext_localconf.php` / `ext_tables.php` according to TYPO3 11

**Comment by Xippo** [comment]
Thanks for your input. I will check this ASAP

Am Mo., 3. Jan. 2022 um 15:21 Uhr schrieb Jens Neumann <
***@***.***>:
