### ISSUE TITLE
Invalid W3C Markup

### ISSUE THREAD

**Issue by Schweriner** [Xippo/OM-Cookie-Manager#21]
https://github.com/Xippo/OM-Cookie-Manager/blob/fb8ffa4b3f97cb85251afaaf5f7a87c9046e9e6f/Resources/Private/Templates/CookiePanel/Show.html#L11

This line is not W3C valid. Attribute checked should not be checked="1", only checked instead. Autocomplete does not exist for input type="check". Change to valid input with:

`<input class="cookie-panel__checkbox {f:if(condition:cookiegroup.essential,then:'cookie-panel__checkbox--state-inactiv',else:'')}" data-omcookie-panel-grp="1" id="group-{cookiegroup.uid}" type="checkbox" {f:if(condition:cookiegroup.essential,then:'checked data-omcookie-panel-essential="1" disabled="disabled"',else:'')} value="group-{cookiegroup.uid}" />`

**Comment by fgeierst** [comment]
+1 for this, I see those issues every time I run the W3C Validator on sites using this extension.
