### ISSUE TITLE
compatible with Typo 3  version 12

### ISSUE THREAD

**Issue by RZivaralam** [Xippo/OM-Cookie-Manager#25]
I would like to know when this plugin will be compatible with Typo 3 version 12?

**Comment by baschte** [comment]
Hey @RZivaralam,
here you can find a PR für TYPO3 11 and 12 compatibility. 
Hope it will be merged and released soon.

#26

**Comment by RZivaralam** [comment]
I'm looking forward to installing new version

**Comment by Xippo** [comment]
@baschte thx a lot for your work. I have merged your pull request. I will do some QA for 11 and 12 and then release a new version

**Comment by baschte** [comment]
@Xippo youre welcome 😁

**Comment by Xippo** [comment]
Compatibility for TYPO3 12 is there.
