### ISSUE TITLE
DEFAULT 0 NOT Null issue with MYSQL 5.5 and TYPO3 8.7 - Incorrect table definition

### ISSUE THREAD

**Issue by tobiasquadflieg** [Xippo/OM-Cookie-Manager#7]
https://github.com/Xippo/OM-Cookie-Manager/blob/c285065d61198470c0317b6f16b0cb19e3d6047a/ext_tables.sql#L5

Seens so that MYSQL 5.5 couldnt handle the 

uid int(11)  NOT NULL auto_increment, statement in combination 
PRIMARY KEY (uid),

it will result in an "Incorrect table definition; there can be only one auto column and it must be defined as a key" error.

This will fix it and will work also MYSQL Version >5.5

uid int(11) unsigned DEFAULT 0 NOT NULL auto_increment,

**Comment by Xippo** [comment]
Thx for reporting this. The uid field is set as key so it should be fine. I tried the sql here:
https://dbfiddle.uk/?rdbms=mysql_5.5&fiddle=99304eb7f93a6c36e2da1c91e8ec63f0
are you sure that your db setup is up to date?

**Comment by Xippo** [comment]
Could not be reproduced.
Closed for inactivity
