### ISSUE TITLE
Bestimmte Cookies pro Sprache ausblenden geht nicht

### ISSUE THREAD

**Issue by meckitt** [Xippo/OM-Cookie-Manager#9]
Erstmal: Super Extension!
Mein Problem ist folgendes... Auf der Website werden mehrere Sprachen verwendet. Jetzt soll auf der deutschen Seite kein Google Analytics verwendet werden... auf der französischen und der englischen aber schon. Wenn ich die deutsche Übersetzung bei Cookies deaktiviere, dann bekomme ich als Fallback Englisch angezeigt.

**Comment by Xippo** [comment]
hi thx for your feedback. It would be nice if we can use english here, maybe you can add a english verison of your question.
I have tried to reproduce your problem with a TYPO3 9 instance and the language settings set on fallback. When i hide a cookie group or a cookie itself i don't get any fallback. Maybe you can try to detach l10n_parent origin (Ursprungstext[l10n_parent]).

//ger
Ich habe versucht das ganze in einem neuener System nachzustellen, mit site Einstellungen auf Fallback gestellt. Wenn ich dann eine Gruppe oder Cookie nur in einer Sprache deaktiviere, weden diese nicht mehr mit ausgegeben. Ggf kannst du versuchen den Ursprungstext[l10n_parent] zu lösen, vielleicht hilft das.

**Comment by Xippo** [comment]
closed due to inactivity
